INSERT INTO "tb_Doctor"
VALUES 
(1, 22, 'Stafford MacAloren', ''),
(2, 18, 'Roarke Hutchence', 'Palliative Care'),
(3, 38, 'Alexa Eefting', 'Critical Care'),
(4, 13, 'Valry Lambswood', 'Palliative Care'),
(5, 9, 'Elana Pumfrett', 'Palliative Care'),
(6, 39, 'Garret Copplestone', 'Palliative Care'),
(7, 62, 'Bebe Duval', ''),
(8, 70, 'Hodge Suston', 'Palliative Care'),
(9, 4, 'Giacobo Spier', 'Critical Care'),
(10, 80, 'Oates Demeza', 'Palliative Care'),
(11, 11, 'Jefferey Winley', 'Critical Care'),
(12, 6, 'Bernhard Reisenstein', 'Palliative Care'),
(13, 15, 'Aaren Leggs', ''),
(14, 32, 'Brigg Baniard', 'Palliative Care'),
(15, 58, 'Cairistiona Gatteridge', 'Critical Care'),
(16, 29, 'Cheston Drust', ''),
(17, 51, 'Nertie Kobiera', 'Palliative Care'),
(18, 98, 'Barnett Brumfitt', 'Palliative Care'),
(19, 91, 'Torie Oldacre', 'Critical Care'),
(20, 67, 'Kathrine Davidesco', 'Critical Care'),
(21, 71, 'Akim Kinavan', 'Critical Care'),
(22, 21, 'Britt Stonham', ''),
(23, 16, 'Hyacinthie Rosthorn', ''),
(24, 85, 'Robert Hunnywell', 'Palliative Care'),
(25, 5, 'Merci Dohmer', 'Critical Care'),
(26, 99, 'Ansel Butland', ''),
(27, 75, 'Windham Andrasch', 'Critical Care'),
(28, 76, 'Tanney McCalum', 'Palliative Care'),
(29, 27, 'Jedd Ligertwood', ''),
(30, 96, 'Ashien Conahy', 'Critical Care'),
(31, 55, 'Claudianus Sibbert', 'Palliative Care'),
(32, 42, 'Porty Bester', 'Critical Care'),
(33, 93, 'Quill McElhinney', ''),
(34, 61, 'Nehemiah Hadden', 'Critical Care'),
(35, 31, 'Darren Tissier', 'Critical Care'),
(36, 23, 'Burg Jeschner', 'Critical Care'),
(37, 74, 'Lyndsie Robinson', 'Critical Care'),
(38, 92, 'Kacie Myhill', 'Critical Care'),
(39, 36, 'Lily Colquyte', 'Critical Care'),
(40, 83, 'Towney Kardos-Stowe', ''),
(41, 35, 'Dunn Leonarde', ''),
(42, 50, 'Laureen Enderle', 'Critical Care'),
(43, 69, 'Gwendolyn Guilford', ''),
(44, 47, 'Ganny Dowber', 'Critical Care'),
(45, 64, 'Boothe Hughf', 'Palliative Care'),
(46, 97, 'Giovanni Juleff', 'Critical Care'),
(47, 40, 'Pauline Beri', 'Palliative Care'),
(48, 81, 'Lesley Weildish', 'Critical Care'),
(49, 28, 'Valdemar Viollet', 'Critical Care'),
(50, 0, 'Perry Gerish', 'Critical Care'),
(51, 43, 'Oran Goligher', 'Critical Care'),
(52, 2, 'Gretna Farmery', ''),
(53, 77, 'Levy Kingsnode', ''),
(54, 84, 'Fidel Hutton', 'Critical Care'),
(55, 1, 'Ashia Pillman', 'Critical Care'),
(56, 48, 'Myrtie Pasby', 'Critical Care'),
(57, 65, 'Lani Jakucewicz', ''),
(58, 14, 'Annaliese Dymond', 'Palliative Care'),
(59, 46, 'Blisse Duckitt', 'Critical Care'),
(60, 95, 'Jeramie Pantridge', 'Critical Care'),
(61, 53, 'Gard Whiffen', ''),
(62, 7, 'Carlotta Eastbrook', 'Palliative Care'),
(63, 56, 'Lisha Pendergrast', ''),
(64, 68, 'Christian Camilleri', ''),
(65, 66, 'Trumann Vesty', ''),
(66, 63, 'Humbert Morde', 'Palliative Care'),
(67, 45, 'Grove Burdikin', 'Critical Care'),
(68, 82, 'Thea Romaine', 'Palliative Care'),
(69, 34, 'Mari Zanelli', ''),
(70, 26, 'Claudie Haken', 'Palliative Care'),
(71, 60, 'Estele Veighey', 'Critical Care'),
(72, 86, 'Kiah Bear', ''),
(73, 79, 'Melvyn Swanne', 'Palliative Care'),
(74, 20, 'Frederica Wemes', 'Palliative Care'),
(75, 52, 'Benedicta Rablin', ''),
(76, 8, 'Zahara Armell', ''),
(77, 89, 'Estel Dean', 'Critical Care'),
(78, 57, 'Constantia Caneo', 'Critical Care'),
(79, 41, 'Belinda Feronet', ''),
(80, 33, 'Caitrin Nelhams', ''),
(81, 90, 'Brian Deal', 'Critical Care'),
(82, 10, 'Margette Carrel', 'Critical Care'),
(83, 17, 'Kellen Fowlestone', ''),
(84, 24, 'Gaby Nott', 'Critical Care'),
(85, 72, 'Kerianne Stroder', 'Palliative Care'),
(86, 30, 'Val Merrywether', 'Palliative Care'),
(87, 54, 'Hannis Semper', ''),
(88, 12, 'Camila Conisbee', 'Critical Care'),
(89, 49, 'Clareta Ellingford', 'Palliative Care'),
(90, 25, 'Julius Glasner', 'Palliative Care'),
(91, 78, 'Ronni Stack', 'Critical Care'),
(92, 73, 'Emelda O Kelleher', 'Palliative Care'),
(93, 19, 'Staffard Griggs', 'Palliative Care'),
(94, 44, 'Aeriela Kopecka', ''),
(95, 3, 'Judd Thaw', 'Palliative Care'),
(96, 59, 'Raphael Sears', ''),
(97, 37, 'Marcellus Graysmark', 'Critical Care'),
(98, 94, 'Dix Quinby', ''),
(99, 87, 'Elyse Kellen', 'Palliative Care'),
(100, 88, 'Richard Baroux', '')